services:
  social-auto-upload:
    build: .
    container_name: social-auto-upload
    restart: always
    ports:
      - "5409:5409"
    volumes:
      - ./videoFile:/app/videoFile
      - ./cookiesFile:/app/cookiesFile
      - ${SAU_CONF_FILE:-./conf.example.py}:/app/conf.py
      - ./data:/app/data
      - ./db:/app/db
    networks:
      1panel-network:
        ipv4_address: 172.18.0.46  # 這是你原本清單中這個容器用的 IP
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - SAU_API_TOKENS=sdkjauashuaiuhHOHEIUFhfaphgeiusdiu545gfdgd
      - META_APP_ID=1541229970910006
      - META_APP_SECRET=48b42e3e140869cd7180cac751295d19
      - SAU_META_CALLBACK_URL=https://socialupload.iamwillywang.com/oauth/meta/callback

networks:
  1panel-network:
    external: true
