XHS_PLATFORM = 1
TENCENT_PLATFORM = 2
DOUYIN_PLATFORM = 3
KUAISHOU_PLATFORM = 4
REDDIT_PLATFORM = 5
X_PLATFORM = 6

PLATFORM_NAMES = {
    XHS_PLATFORM: "小红书",
    TENCENT_PLATFORM: "视频号",
    DOUYIN_PLATFORM: "抖音",
    KUAISHOU_PLATFORM: "快手",
    REDDIT_PLATFORM: "Reddit",
    X_PLATFORM: "X",
}

OAUTH_PLATFORM_TYPES = {REDDIT_PLATFORM, X_PLATFORM}
LEGACY_PLATFORM_TYPES = {XHS_PLATFORM, TENCENT_PLATFORM, DOUYIN_PLATFORM, KUAISHOU_PLATFORM}
SOCIAL_PLATFORM_TYPES = {REDDIT_PLATFORM, X_PLATFORM}


def get_platform_name(platform_type):
    return PLATFORM_NAMES.get(platform_type, "未知平台")


def is_oauth_platform(platform_type):
    return platform_type in OAUTH_PLATFORM_TYPES
